#dev
#9900
#H2
#prod
#9943
#mysql

spring:
  application:
    name: AccountsService
  profiles.active: prod

---
spring:
  config.activate.on-profile: dev
  sql.init.mode: always
  devtools.restart.enabled: true
  datasource:
    url: "jdbc:h2:mem:accountsdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server.port: 9900


---
spring:
  config.activate.on-profile: prod
  sql.init.mode: always
  devtools.restart.enabled: true
  application:
    name: AccountsService
  datasource:
    url: "jdbc:mysql:mem:accountsdb"
    driverClassName: com.mysql.jdbc.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: false


server.port: 9943
